### ISSUE TITLE
No Such Table

### ISSUE THREAD

**Issue by DavidMagda** [dewv/mmvece#4]
When testing the student model, there are errors with tables not being created that should be created by another service.

**Comment by smattingly** [comment]
Some of these problems can be suppressed, but only with lots of work. Even then, some tests will have to be "pending" (not run) until other services are available, and we would have to come back to run those tests. The fundamental problem is that relational database designs cannot be separated into pieces the way that the services are. The short term way to deal with this is to carefully order which services are built first; building Staff before Student would have avoided this problem. The long term solution is to move from a relational database to a more suitable model like MongoDB.
